# Generated by Django 3.1.7 on 2021-03-06 22:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klass',
            options={'ordering': ('-is_active', 'klass_name')},
        ),
        migrations.AlterField(
            model_name='klass',
            name='end_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='klass',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='klass',
            name='start_year',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='student',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
