# Generated by Django 3.1.7 on 2021-03-06 22:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210306_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2021, 3, 6)),
            preserve_default=False,
        ),
    ]
