# Generated by Django 3.0.8 on 2020-07-02 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200702_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_adminstrator',
            new_name='is_administrator',
        ),
    ]
