# Generated by Django 3.1.7 on 2021-03-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210307_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sex',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F')], default=1, max_length=8),
            preserve_default=False,
        ),
    ]
