# Generated by Django 3.1.7 on 2021-03-08 00:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210307_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.DateField(default=django.utils.timezone.now)),
                ('end_year', models.DateField()),
            ],
        ),
    ]
