# Generated by Django 3.1.7 on 2021-03-08 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_academicyear_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='klass',
            name='academic_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='klasses', to='accounts.academicyear'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='klass',
            unique_together={('academic_year', 'klass_name')},
        ),
    ]
