# Generated by Django 3.1.7 on 2021-03-12 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210308_0035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={'ordering': ('-is_active', '-start_year')},
        ),
    ]
