# Generated by Django 3.1.7 on 2021-03-17 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210312_0927'),
        ('accounts', '0013_noticeboard'),
    ]

    operations = [
    ]
