# Generated by Django 3.1.7 on 2021-03-17 12:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_merge_20210317_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('name', '-is_active', '-date_created')},
        ),
        migrations.AlterModelOptions(
            name='noticeboard',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AddField(
            model_name='course',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 3, 17, 12, 55, 28, 369879, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='noticeboard',
            name='date',
            field=models.DateTimeField(help_text='add date if event has a date', null=True),
        ),
    ]
